"""
Message card builders for Slack (Block Kit) and Microsoft Teams (HTML/Adaptive Cards).

Each builder function returns:
  - For Slack: { "text": str, "blocks": list } — Block Kit JSON
  - For Teams: { "content": str, "content_type": "html" } — HTML body

Notification types:
  - standup_report: Daily standup report for a developer
  - standup_digest: Team standup digest for PO
  - blocker_alert: Blocker flag raised by a developer
  - sprint_approval: Sprint plan ready for PO approval
  - health_alert: Burnout/workload health alert (PO DM only)
  - sprint_assignment: New sprint task assigned to developer
  - ci_failure: CI/CD pipeline failure alert
  - retro_action: Retrospective action item assigned

IMPORTANT: All interactive buttons include a JSON-encoded `value` field
containing action context (IDs, names, org_id) so the Slack interaction
handler knows what resource to update when the button is clicked.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from ..config import settings

FRONTEND_URL = settings.frontend_url


# ===================================================================
# SLACK BLOCK KIT BUILDERS
# ===================================================================

def slack_standup_report(
    dev_name: str,
    yesterday: list[str],
    today: list[str],
    blockers: list[str],
    sprint_name: str = "",
    *,
    report_id: str = "",
    org_id: str = "",
) -> dict:
    """Daily standup report delivered to developer DM."""
    blocks: list[dict[str, Any]] = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": "📋 Your Daily Standup Report"},
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"Good morning, *{dev_name}*! Here's your auto-generated standup:"
                + (f" _{sprint_name}_" if sprint_name else ""),
            },
        },
        {"type": "divider"},
    ]

    # Yesterday
    if yesterday:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*✅ Yesterday:*\n" + "\n".join(f"• {item}" for item in yesterday),
            },
        })

    # Today
    if today:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*📌 Today:*\n" + "\n".join(f"• {item}" for item in today),
            },
        })

    # Blockers
    if blockers:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": ":rotating_light: *Blockers:*\n" + "\n".join(f"• {b}" for b in blockers),
            },
        })

    blocks.extend([
        {"type": "divider"},
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "View in Plan2Sprint"},
                    "url": f"{FRONTEND_URL}/dev/standups",
                    "style": "primary",
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "🚩 Flag a Blocker"},
                    "action_id": "flag_blocker",
                    "style": "danger",
                    "value": json.dumps({
                        "report_id": report_id,
                        "org_id": org_id,
                    }),
                },
            ],
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"Auto-generated by Plan2Sprint at {datetime.now(timezone.utc).strftime('%H:%M UTC')}",
                }
            ],
        },
    ])

    return {
        "text": f"Standup Report for {dev_name}",
        "blocks": blocks,
    }


def slack_blocker_alert(
    dev_name: str,
    ticket_key: str,
    ticket_title: str,
    blocker_description: str,
    days_blocked: int = 0,
    *,
    blocker_id: str = "",
    org_id: str = "",
) -> dict:
    """Blocker flag notification sent to PO — with Acknowledge + Escalate buttons."""
    action_context = json.dumps({
        "blocker_id": blocker_id,
        "ticket_key": ticket_key,
        "org_id": org_id,
    })

    blocks: list[dict[str, Any]] = [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f":rotating_light: *Blocker Flagged by {dev_name}*",
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Ticket:*\n{ticket_key}: {ticket_title}"},
                {"type": "mrkdwn", "text": f"*Blocked for:*\n{days_blocked} day{'s' if days_blocked != 1 else ''}"},
            ],
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Description:*\n{blocker_description}",
            },
        },
        {"type": "divider"},
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "✅ Acknowledge"},
                    "action_id": "acknowledge_blocker",
                    "style": "primary",
                    "value": action_context,
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "🚨 Escalate"},
                    "action_id": "escalate_blocker",
                    "style": "danger",
                    "value": action_context,
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "View Details"},
                    "url": f"{FRONTEND_URL}/po/standups",
                },
            ],
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Flagged at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint"},
            ],
        },
    ]

    return {
        "text": f"🚨 Blocker flagged by {dev_name}: {ticket_key}",
        "blocks": blocks,
    }


def slack_sprint_approval(
    sprint_name: str,
    total_points: int,
    ticket_count: int,
    team_name: str = "",
    *,
    plan_id: str = "",
    org_id: str = "",
) -> dict:
    """Sprint plan approval request sent to PO — with Approve + Reject buttons."""
    action_context = json.dumps({
        "plan_id": plan_id,
        "sprint_name": sprint_name,
        "org_id": org_id,
    })

    blocks: list[dict[str, Any]] = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": "📋 Sprint Plan Ready for Approval"},
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "A new sprint plan has been generated and needs your review.",
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Sprint:*\n{sprint_name}"},
                {"type": "mrkdwn", "text": f"*Team:*\n{team_name or 'Default'}"},
                {"type": "mrkdwn", "text": f"*Story Points:*\n{total_points}"},
                {"type": "mrkdwn", "text": f"*Tickets:*\n{ticket_count}"},
            ],
        },
        {"type": "divider"},
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "✅ Approve Sprint"},
                    "action_id": "approve_sprint",
                    "style": "primary",
                    "value": action_context,
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "❌ Reject"},
                    "action_id": "reject_sprint",
                    "style": "danger",
                    "value": action_context,
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Review in App"},
                    "url": f"{FRONTEND_URL}/po/planning",
                },
            ],
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Generated at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint"},
            ],
        },
    ]

    return {
        "text": f"Sprint plan '{sprint_name}' ready for approval ({total_points} SP, {ticket_count} tickets)",
        "blocks": blocks,
    }


def slack_health_alert(
    member_name: str,
    alert_type: str,
    severity: str,
    details: str,
    *,
    alert_id: str = "",
    org_id: str = "",
) -> dict:
    """Burnout/health alert sent to PO DM only — never in channels."""
    severity_emoji = {
        "high": ":red_circle:",
        "medium": ":large_orange_circle:",
        "low": ":large_yellow_circle:",
    }.get(severity.lower(), ":warning:")

    action_context = json.dumps({
        "alert_id": alert_id,
        "member_name": member_name,
        "org_id": org_id,
    })

    blocks: list[dict[str, Any]] = [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"{severity_emoji} *Health Alert: {alert_type}*",
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Team Member:*\n{member_name}"},
                {"type": "mrkdwn", "text": f"*Severity:*\n{severity.capitalize()}"},
            ],
        },
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Details:*\n{details}"},
        },
        {"type": "divider"},
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "🔇 Snooze 24h"},
                    "action_id": "snooze_alert",
                    "value": action_context,
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "View Team Health"},
                    "url": f"{FRONTEND_URL}/po/health",
                    "style": "primary",
                },
            ],
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": ":lock: This alert is visible only to you. • Plan2Sprint",
                }
            ],
        },
    ]

    return {
        "text": f"Health alert for {member_name}: {alert_type}",
        "blocks": blocks,
    }


# ===================================================================
# RETROSPECTIVE SUMMARY (PO sends to team channel)
# ===================================================================

def slack_retro_summary(
    sprint_name: str,
    action_items: list[str],
    top_theme: str = "",
    went_well: list[str] | None = None,
    to_improve: list[str] | None = None,
    *,
    retro_id: str = "",
    org_id: str = "",
) -> dict:
    """Sprint retrospective summary pushed to team channel by PO."""
    well_items = went_well or []
    improve_items = to_improve or []

    well_text = "\n".join(f"• {item}" for item in well_items) if well_items else "_None recorded_"
    improve_text = "\n".join(f"• {item}" for item in improve_items) if improve_items else "_None recorded_"
    action_text = "\n".join(f"• {item}" for item in action_items) if action_items else "_No action items_"

    blocks: list[dict[str, Any]] = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"📝 Retrospective Summary — {sprint_name}"},
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Top Theme:* {top_theme}" if top_theme else "*Retrospective outcomes from your PO:*",
            },
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*✅ What went well:*\n{well_text}",
            },
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*🔧 To improve:*\n{improve_text}",
            },
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*📌 Action Items:*\n{action_text}",
            },
        },
        {"type": "divider"},
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "View Full Retro"},
                    "url": f"{FRONTEND_URL}/po/retrospective",
                    "style": "primary",
                },
            ],
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Shared at {datetime.now(timezone.utc).strftime('%H:%M UTC')} by your Product Owner • Plan2Sprint"},
            ],
        },
    ]

    return {
        "text": f"Retrospective Summary — {sprint_name}",
        "blocks": blocks,
    }


# ===================================================================
# BLOCKER FLAG (Developer raises a blocker via Slack)
# ===================================================================

def slack_flag_blocker(
    dev_name: str,
    ticket_key: str,
    ticket_title: str,
    blocker_description: str,
    *,
    blocker_id: str = "",
    org_id: str = "",
) -> dict:
    """Developer-initiated blocker flag — sends to PO's DM with Acknowledge + Escalate."""
    action_context = json.dumps({
        "blocker_id": blocker_id,
        "ticket_key": ticket_key,
        "org_id": org_id,
    })

    blocks: list[dict[str, Any]] = [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f":rotating_light: *Blocker Flagged by {dev_name}*",
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Ticket:*\n{ticket_key}: {ticket_title}"},
                {"type": "mrkdwn", "text": f"*Raised by:*\n{dev_name}"},
            ],
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Description:*\n{blocker_description}",
            },
        },
        {"type": "divider"},
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "✅ Acknowledge"},
                    "action_id": "acknowledge_blocker",
                    "style": "primary",
                    "value": action_context,
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "🚨 Escalate"},
                    "action_id": "escalate_blocker",
                    "style": "danger",
                    "value": action_context,
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "View in Plan2Sprint"},
                    "url": f"{FRONTEND_URL}/po/standups",
                },
            ],
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Flagged at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint"},
            ],
        },
    ]

    return {
        "text": f"🚨 Blocker flagged by {dev_name}: {ticket_key}",
        "blocks": blocks,
    }


# ===================================================================
# TEAMS HTML BUILDERS
# ===================================================================

def teams_standup_report(
    dev_name: str,
    yesterday: list[str],
    today: list[str],
    blockers: list[str],
    sprint_name: str = "",
) -> dict:
    """Daily standup report for Teams chat."""
    yesterday_html = "".join(f"<li>{item}</li>" for item in yesterday)
    today_html = "".join(f"<li>{item}</li>" for item in today)
    blockers_html = "".join(f"<li>{b}</li>" for b in blockers) if blockers else ""

    content = f"""
<div>
  <h3>📋 Your Daily Standup Report</h3>
  <p>Good morning, <strong>{dev_name}</strong>! Here's your auto-generated standup{f' for <em>{sprint_name}</em>' if sprint_name else ''}:</p>
  <hr/>
  <p><strong>✅ Yesterday:</strong></p>
  <ul>{yesterday_html}</ul>
  <p><strong>📌 Today:</strong></p>
  <ul>{today_html}</ul>
  {"<p><strong>🚨 Blockers:</strong></p><ul>" + blockers_html + "</ul>" if blockers_html else ""}
  <hr/>
  <p><a href="{FRONTEND_URL}/dev/standups">View in Plan2Sprint</a></p>
  <p style="color: #666; font-size: 12px;">Auto-generated by Plan2Sprint at {datetime.now(timezone.utc).strftime('%H:%M UTC')}</p>
</div>
""".strip()

    return {"content": content, "content_type": "html"}


def teams_blocker_alert(
    dev_name: str,
    ticket_key: str,
    ticket_title: str,
    blocker_description: str,
    days_blocked: int = 0,
) -> dict:
    """Blocker flag notification for Teams."""
    content = f"""
<div>
  <h3>🚨 Blocker Flagged by {dev_name}</h3>
  <table>
    <tr><td><strong>Ticket:</strong></td><td>{ticket_key}: {ticket_title}</td></tr>
    <tr><td><strong>Blocked for:</strong></td><td>{days_blocked} day{'s' if days_blocked != 1 else ''}</td></tr>
  </table>
  <p><strong>Description:</strong> {blocker_description}</p>
  <hr/>
  <p><a href="{FRONTEND_URL}/po/standups">View Details in Plan2Sprint</a></p>
  <p style="color: #666; font-size: 12px;">Flagged at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint</p>
</div>
""".strip()

    return {"content": content, "content_type": "html"}


def teams_sprint_approval(
    sprint_name: str,
    total_points: int,
    ticket_count: int,
    team_name: str = "",
) -> dict:
    """Sprint plan approval request for Teams."""
    content = f"""
<div>
  <h3>📋 Sprint Plan Ready for Approval</h3>
  <p>A new sprint plan has been generated and needs your review.</p>
  <table>
    <tr><td><strong>Sprint:</strong></td><td>{sprint_name}</td></tr>
    <tr><td><strong>Team:</strong></td><td>{team_name or 'Default'}</td></tr>
    <tr><td><strong>Story Points:</strong></td><td>{total_points}</td></tr>
    <tr><td><strong>Tickets:</strong></td><td>{ticket_count}</td></tr>
  </table>
  <hr/>
  <p><a href="{FRONTEND_URL}/po/planning">Review & Approve in Plan2Sprint</a></p>
  <p style="color: #666; font-size: 12px;">Generated at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint</p>
</div>
""".strip()

    return {"content": content, "content_type": "html"}


def teams_health_alert(
    member_name: str,
    alert_type: str,
    severity: str,
    details: str,
) -> dict:
    """Health alert for Teams — PO DM only."""
    severity_color = {
        "high": "#DC2626",
        "medium": "#F59E0B",
        "low": "#EAB308",
    }.get(severity.lower(), "#F59E0B")

    content = f"""
<div>
  <h3 style="color: {severity_color};">⚠️ Health Alert: {alert_type}</h3>
  <table>
    <tr><td><strong>Team Member:</strong></td><td>{member_name}</td></tr>
    <tr><td><strong>Severity:</strong></td><td>{severity.capitalize()}</td></tr>
  </table>
  <p><strong>Details:</strong> {details}</p>
  <hr/>
  <p><a href="{FRONTEND_URL}/po/health">View Team Health in Plan2Sprint</a></p>
  <p style="color: #666; font-size: 12px;">🔒 This alert is visible only to you. • Plan2Sprint</p>
</div>
""".strip()

    return {"content": content, "content_type": "html"}


# ===================================================================
# TEAMS: RETROSPECTIVE SUMMARY
# ===================================================================

def teams_retro_summary(
    sprint_name: str,
    action_items: list[str],
    top_theme: str = "",
    went_well: list[str] | None = None,
    to_improve: list[str] | None = None,
) -> dict:
    """Sprint retrospective summary for Teams."""
    well_html = "".join(f"<li>{item}</li>" for item in (went_well or []))
    improve_html = "".join(f"<li>{item}</li>" for item in (to_improve or []))
    action_html = "".join(f"<li>{item}</li>" for item in action_items) if action_items else "<li><em>No action items</em></li>"

    content = f"""
<div>
  <h3>📝 Retrospective Summary — {sprint_name}</h3>
  {f'<p><strong>Top Theme:</strong> {top_theme}</p>' if top_theme else ''}
  <hr/>
  <p><strong>✅ What went well:</strong></p>
  <ul>{well_html or '<li><em>None recorded</em></li>'}</ul>
  <p><strong>🔧 To improve:</strong></p>
  <ul>{improve_html or '<li><em>None recorded</em></li>'}</ul>
  <p><strong>📌 Action Items:</strong></p>
  <ul>{action_html}</ul>
  <hr/>
  <p><a href="{FRONTEND_URL}/po/retrospective">View Full Retro in Plan2Sprint</a></p>
  <p style="color: #666; font-size: 12px;">Shared at {datetime.now(timezone.utc).strftime('%H:%M UTC')} by your Product Owner • Plan2Sprint</p>
</div>
""".strip()

    return {"content": content, "content_type": "html"}


# ===================================================================
# TEAMS: FLAG BLOCKER (developer-initiated)
# ===================================================================

def teams_flag_blocker(
    dev_name: str,
    ticket_key: str,
    ticket_title: str,
    blocker_description: str,
) -> dict:
    """Developer-initiated blocker flag for Teams — sends to PO chat."""
    content = f"""
<div>
  <h3>🚨 Blocker Flagged by {dev_name}</h3>
  <table>
    <tr><td><strong>Ticket:</strong></td><td>{ticket_key}: {ticket_title}</td></tr>
    <tr><td><strong>Raised by:</strong></td><td>{dev_name}</td></tr>
  </table>
  <p><strong>Description:</strong> {blocker_description}</p>
  <hr/>
  <p><a href="{FRONTEND_URL}/po/standups">View in Plan2Sprint</a></p>
  <p style="color: #666; font-size: 12px;">Flagged at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint</p>
</div>
""".strip()

    return {"content": content, "content_type": "html"}


# ===================================================================
# SLACK + TEAMS: SPRINT ASSIGNMENT (developer notification)
# ===================================================================

def slack_sprint_assignment(
    dev_name: str,
    ticket_key: str,
    ticket_title: str,
    sprint_name: str,
    story_points: int = 0,
    *,
    org_id: str = "",
) -> dict:
    """Sprint task assigned to developer — Slack DM."""
    blocks: list[dict[str, Any]] = [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "📋 *New Sprint Assignment*",
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Ticket:*\n{ticket_key}: {ticket_title}"},
                {"type": "mrkdwn", "text": f"*Sprint:*\n{sprint_name}"},
                {"type": "mrkdwn", "text": f"*Story Points:*\n{story_points}"},
                {"type": "mrkdwn", "text": f"*Assigned to:*\n{dev_name}"},
            ],
        },
        {"type": "divider"},
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "View My Sprint"},
                    "url": f"{FRONTEND_URL}/dev/sprint",
                    "style": "primary",
                },
            ],
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Assigned at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint"},
            ],
        },
    ]

    return {
        "text": f"New sprint assignment: {ticket_key} ({sprint_name})",
        "blocks": blocks,
    }


def teams_sprint_assignment(
    dev_name: str,
    ticket_key: str,
    ticket_title: str,
    sprint_name: str,
    story_points: int = 0,
) -> dict:
    """Sprint task assigned to developer — Teams chat."""
    content = f"""
<div>
  <h3>📋 New Sprint Assignment</h3>
  <table>
    <tr><td><strong>Ticket:</strong></td><td>{ticket_key}: {ticket_title}</td></tr>
    <tr><td><strong>Sprint:</strong></td><td>{sprint_name}</td></tr>
    <tr><td><strong>Story Points:</strong></td><td>{story_points}</td></tr>
    <tr><td><strong>Assigned to:</strong></td><td>{dev_name}</td></tr>
  </table>
  <hr/>
  <p><a href="{FRONTEND_URL}/dev/sprint">View My Sprint in Plan2Sprint</a></p>
  <p style="color: #666; font-size: 12px;">Assigned at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint</p>
</div>
""".strip()

    return {"content": content, "content_type": "html"}


# ===================================================================
# SLACK + TEAMS: CI/CD FAILURE ALERT (developer notification)
# ===================================================================

def slack_ci_failure(
    dev_name: str,
    repo_name: str,
    branch: str,
    pr_title: str = "",
    failure_summary: str = "",
    run_url: str = "",
    *,
    org_id: str = "",
) -> dict:
    """CI/CD pipeline failure alert — Slack DM to developer."""
    blocks: list[dict[str, Any]] = [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": ":x: *CI/CD Pipeline Failed*",
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Repository:*\n{repo_name}"},
                {"type": "mrkdwn", "text": f"*Branch:*\n`{branch}`"},
            ],
        },
    ]

    if pr_title:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*PR:*\n{pr_title}"},
        })

    if failure_summary:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Failure:*\n```{failure_summary}```"},
        })

    action_elements: list[dict[str, Any]] = []
    if run_url:
        action_elements.append({
            "type": "button",
            "text": {"type": "plain_text", "text": "View Build Log"},
            "url": run_url,
            "style": "danger",
        })
    action_elements.append({
        "type": "button",
        "text": {"type": "plain_text", "text": "View My GitHub"},
        "url": f"{FRONTEND_URL}/dev/github",
        "style": "primary",
    })

    blocks.extend([
        {"type": "divider"},
        {"type": "actions", "elements": action_elements},
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Detected at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint"},
            ],
        },
    ])

    return {
        "text": f"CI/CD failed on {repo_name}/{branch}",
        "blocks": blocks,
    }


def teams_ci_failure(
    dev_name: str,
    repo_name: str,
    branch: str,
    pr_title: str = "",
    failure_summary: str = "",
    run_url: str = "",
) -> dict:
    """CI/CD pipeline failure alert — Teams chat."""
    content = f"""
<div>
  <h3 style="color: #DC2626;">❌ CI/CD Pipeline Failed</h3>
  <table>
    <tr><td><strong>Repository:</strong></td><td>{repo_name}</td></tr>
    <tr><td><strong>Branch:</strong></td><td><code>{branch}</code></td></tr>
    {f'<tr><td><strong>PR:</strong></td><td>{pr_title}</td></tr>' if pr_title else ''}
  </table>
  {f'<p><strong>Failure:</strong></p><pre>{failure_summary}</pre>' if failure_summary else ''}
  <hr/>
  {f'<p><a href="{run_url}">View Build Log</a> | ' if run_url else '<p>'}
  <a href="{FRONTEND_URL}/dev/github">View My GitHub in Plan2Sprint</a></p>
  <p style="color: #666; font-size: 12px;">Detected at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint</p>
</div>
""".strip()

    return {"content": content, "content_type": "html"}


# ===================================================================
# SLACK + TEAMS: RETRO ACTION ITEM (developer notification)
# ===================================================================

def slack_retro_action(
    dev_name: str,
    action_item: str,
    sprint_name: str,
    *,
    retro_id: str = "",
    org_id: str = "",
) -> dict:
    """Retrospective action item assigned to developer — Slack DM."""
    blocks: list[dict[str, Any]] = [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "📌 *Retro Action Item Assigned to You*",
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Sprint:*\n{sprint_name}"},
                {"type": "mrkdwn", "text": f"*Assigned to:*\n{dev_name}"},
            ],
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Action Item:*\n{action_item}",
            },
        },
        {"type": "divider"},
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "View Retro Details"},
                    "url": f"{FRONTEND_URL}/dev/sprint",
                    "style": "primary",
                },
            ],
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Assigned at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint"},
            ],
        },
    ]

    return {
        "text": f"Retro action item assigned: {action_item[:50]}",
        "blocks": blocks,
    }


def teams_retro_action(
    dev_name: str,
    action_item: str,
    sprint_name: str,
) -> dict:
    """Retrospective action item assigned to developer — Teams chat."""
    content = f"""
<div>
  <h3>📌 Retro Action Item Assigned to You</h3>
  <table>
    <tr><td><strong>Sprint:</strong></td><td>{sprint_name}</td></tr>
    <tr><td><strong>Assigned to:</strong></td><td>{dev_name}</td></tr>
  </table>
  <p><strong>Action Item:</strong> {action_item}</p>
  <hr/>
  <p><a href="{FRONTEND_URL}/dev/sprint">View Sprint Details in Plan2Sprint</a></p>
  <p style="color: #666; font-size: 12px;">Assigned at {datetime.now(timezone.utc).strftime('%H:%M UTC')} • Plan2Sprint</p>
</div>
""".strip()

    return {"content": content, "content_type": "html"}
