"""Timeline engine — the single source of truth for the PO dashboard timeline.

A project's timeline can be generated by one of three modes, selected via
``determine_mode``:

    RAW          — no approved AI plan. Dates derived straight from ADO/Jira
                   feature ``planned_start``/``planned_end`` values, grouped
                   into phases by the existing phase-assignment engine.
    AI_OPTIMIZED — an AI SprintPlan has been approved. Dates derived from the
                   plan's sprint allocations. Phases are constrained: no phase
                   may end after ``ImportedProject.target_launch_date``.
                   (Implemented in Sprint 3.)
    REBALANCED   — the active plan is a rebalance of a prior AI plan. Same as
                   AI_OPTIMIZED but the target_launch_date itself may have been
                   pushed forward by acceptance of the rebalance. (Sprint 3.)

Layer 2 ("real-time adjustment") — picking the *current* phase from live ADO
state and GitHub activity — is added in Sprint 5.

Sprint 1 delivered the data model (Ready phase + target_launch_date +
planned_start/planned_end columns). This module (Sprint 2) delivers the Raw
mode. Sprints 3-5 extend it with AI/Rebalanced modes and the real-time layer.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import case, select, func, or_, and_
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import aliased

from ..models.imported_project import ImportedProject
from ..models.project_phase import ProjectPhase
from ..models.work_item import WorkItem

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Public types
# ---------------------------------------------------------------------------

TimelineMode = str  # "RAW" | "AI_OPTIMIZED" | "REBALANCED"

MODE_RAW = "RAW"
MODE_AI_OPTIMIZED = "AI_OPTIMIZED"
MODE_REBALANCED = "REBALANCED"


@dataclass
class TimelinePhase:
    """Serialisable snapshot of a single phase on the timeline."""
    id: str
    slug: str
    name: str
    sort_order: int
    color: str
    planned_start: Optional[datetime]
    planned_end: Optional[datetime]


@dataclass
class TimelineDTO:
    """What ``compute_timeline`` returns — everything the PO dashboard needs
    to render the hero banner timeline without doing date math of its own."""
    mode: TimelineMode
    phases: list[TimelinePhase] = field(default_factory=list)
    # The enforceable deadline the plan is measured against. May be None in
    # pure Raw mode if ADO/Jira has no end dates yet — UI renders "TBD".
    target_launch_date: Optional[datetime] = None
    # "AUTO" | "MANUAL" | None. MANUAL means the PO hand-edited the target.
    target_launch_source: Optional[str] = None
    # True when at least one phase end is beyond target_launch_date. Only
    # meaningful in AI/Rebalanced modes (Raw has no enforced target).
    target_violated: bool = False
    target_violated_days: int = 0

    # ---- Real-time adjustment (Sprint 5) ----
    # The phase the project is CURRENTLY in, according to live signals.
    # In Raw mode this comes from ADO/Jira only. In AI/Rebalanced modes we
    # also check GitHub commit activity and take whichever source shows the
    # most advanced phase — GitHub reflects actual dev progress while ADO
    # cards often lag.
    current_phase_slug: Optional[str] = None
    # "ADO" | "GITHUB" | "BOTH" | None. Tells the UI which signal produced
    # the current-phase decision so it can tooltip the reason.
    current_phase_source: Optional[str] = None
    # Hotfix 16 — phases EARLIER than ``current_phase_slug`` that still have
    # in-flight work. The UI renders these in a distinct "also active"
    # colour (cyan glow) alongside the orange "current" indicator,
    # answering "we've reached Deployment, but Testing still has loose
    # ends" without conflating the two states.
    also_active_phase_slugs: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Mode detection
# ---------------------------------------------------------------------------

async def determine_mode(
    db: AsyncSession,
    project: ImportedProject,
) -> TimelineMode:
    """Pick RAW / AI_OPTIMIZED / REBALANCED for this project.

    Rules (in order):
      1. If the project has an APPROVED / SYNCED SprintPlan marked
         ``is_rebalanced=True``  → REBALANCED.
      2. Else if it has an APPROVED / SYNCED SprintPlan  → AI_OPTIMIZED.
      3. Else                                            → RAW.

    Sprint 2 returns RAW for everything that isn't obviously in AI/Rebalanced
    modes — full wiring for the other two modes lands in Sprint 3, but the
    detection is already correct so callers can switch on the result now.
    """
    # Delayed import to avoid a circular dep during module load.
    try:
        from ..models.sprint_plan import SprintPlan  # type: ignore
    except Exception:  # noqa: BLE001 - tolerant import
        return MODE_RAW

    accepted_states = ("APPROVED", "SYNCED", "SYNCED_PARTIAL")
    q = await db.execute(
        select(SprintPlan)
        .where(
            SprintPlan.project_id == project.id,
            SprintPlan.status.in_(accepted_states),
        )
        .order_by(SprintPlan.created_at.desc())
    )
    plan = q.scalars().first()
    if plan is None:
        return MODE_RAW
    if getattr(plan, "is_rebalanced", False):
        return MODE_REBALANCED
    return MODE_AI_OPTIMIZED


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

async def compute_timeline(
    db: AsyncSession,
    org_id: str,
    project_id: str,
    persist: bool = True,
) -> TimelineDTO:
    """Compute the timeline for a project and optionally persist phase dates.

    ``persist=True`` (default) writes the computed ``planned_start`` /
    ``planned_end`` back onto the ``project_phases`` rows so subsequent reads
    don't have to recompute. Callers that just want a read-only peek can pass
    ``persist=False``.
    """
    project = await _load_project(db, org_id, project_id)
    if project is None:
        return TimelineDTO(mode=MODE_RAW)

    mode = await determine_mode(db, project)

    if mode == MODE_RAW:
        timeline = await _compute_raw_timeline(db, project)
    elif mode == MODE_AI_OPTIMIZED:
        timeline = await _compute_ai_timeline(db, project)
    elif mode == MODE_REBALANCED:
        timeline = await _compute_rebalanced_timeline(db, project)
    else:
        # Unreachable under the current determine_mode(), but keeps us safe
        # against someone adding a new mode without wiring it up.
        logger.warning("timeline_engine: unknown mode=%s — falling back to RAW", mode)
        timeline = await _compute_raw_timeline(db, project)
        timeline.mode = mode

    # Layer 2 — real-time adjustment. Pick the "current" phase based on live
    # ADO and GitHub signals. In Raw mode we ignore GitHub by design.
    await _apply_realtime_adjustment(db, project, timeline)

    if persist:
        await _persist_phase_dates(db, timeline.phases)

    return timeline


# ---------------------------------------------------------------------------
# Layer 2 — real-time adjustment
# ---------------------------------------------------------------------------

async def _apply_realtime_adjustment(
    db: AsyncSession,
    project: ImportedProject,
    timeline: TimelineDTO,
) -> None:
    """Set ``timeline.current_phase_slug`` + ``current_phase_source``.

    Logic:
      - ado_slug = phase with the highest sort_order that has ≥1 work item
        NOT in a backlog/new/todo status. This is the "most advanced" phase
        ADO/Jira says we've reached.
      - gh_slug  = output of commit_matcher.infer_github_phase() — the most
        advanced phase inferred from recent commit messages.
      - RAW mode:          current = ado_slug
      - AI/REBALANCED:     current = max(ado_slug, gh_slug) by sort_order
      - source             = "ADO" / "GITHUB" / "BOTH" / None

    Why favour GitHub when it's ahead? Because commits prove work actually
    landed. ADO cards often lag because no one bothered to drag them across.
    """
    ado_slug, ado_also_active = await _infer_ado_phase(db, project)
    gh_slug: Optional[str] = None
    if timeline.mode != MODE_RAW:
        try:
            from .commit_matcher import infer_github_phase  # local import
            gh_slug = await infer_github_phase(
                db, project.organization_id, project.id
            )
        except Exception as e:  # noqa: BLE001 - don't let GH failures blow up the timeline
            logger.warning("commit_matcher failed: %s", e)
            gh_slug = None

    # Build a sort_order lookup from the phases we already loaded.
    sort_by_slug: dict[str, int] = {p.slug: p.sort_order for p in timeline.phases}

    candidates: list[tuple[str, str]] = []  # (source, slug)
    if ado_slug is not None:
        candidates.append(("ADO", ado_slug))
    if gh_slug is not None:
        candidates.append(("GITHUB", gh_slug))

    if not candidates:
        timeline.current_phase_slug = None
        timeline.current_phase_source = None
        timeline.also_active_phase_slugs = []
        return

    # Pick winner by highest sort_order; if tied, use BOTH.
    candidates.sort(key=lambda c: sort_by_slug.get(c[1], -1), reverse=True)
    top_order = sort_by_slug.get(candidates[0][1], -1)
    top = [c for c in candidates if sort_by_slug.get(c[1], -1) == top_order]

    if len(top) == 1:
        source, slug = top[0]
        timeline.current_phase_slug = slug
        timeline.current_phase_source = source
    else:
        # Both sources agree on the same phase
        timeline.current_phase_slug = top[0][1]
        timeline.current_phase_source = "BOTH"

    # Hotfix 16 — populate "also active" loose-ends. We only have
    # ADO-side detail for in-flight stragglers (commit_matcher gives a
    # single phase, not a list). If GitHub picked a more advanced phase
    # than ADO, recompute relative to GH's pick: any phase between ADO's
    # pick and GH's pick that ADO still has in-flight should be flagged.
    final_current_order = sort_by_slug.get(timeline.current_phase_slug or "", -1)
    timeline.also_active_phase_slugs = [
        slug
        for slug in ado_also_active
        if sort_by_slug.get(slug, -1) < final_current_order
    ]
    # If ADO was the source and ado_slug == final, ado_also_active is
    # already correct. If GH is ahead, we additionally flag the
    # ADO-current phase itself as "also active" — work IS happening
    # there, even if GitHub commits have already moved past it.
    if (
        ado_slug
        and timeline.current_phase_slug != ado_slug
        and sort_by_slug.get(ado_slug, -1) < final_current_order
        and ado_slug not in timeline.also_active_phase_slugs
    ):
        timeline.also_active_phase_slugs.append(ado_slug)


async def _infer_ado_phase(
    db: AsyncSession,
    project: ImportedProject,
) -> tuple[Optional[str], list[str]]:
    """Figure out which phase ADO/Jira says the project has reached, plus
    any earlier phases that are still actively being worked on.

    Hotfix 16 — corrected definition of "current phase".
    -----------------------------------------------------
    The previous logic ran two passes: in-flight first, finished as
    fallback. That meant a project with Testing in-flight + Deployment
    DONE would report Testing as current — ignoring the fact that the
    project's frontier has clearly advanced past Testing.

    The new rule: **current = the most-advanced phase that has been
    touched at all** (in-flight OR finished). Touching a phase is proof
    the project reached it. Stragglers in earlier phases are tracked
    separately as ``also_active_phase_slugs`` so the UI can render
    "we're in Deployment, and Testing still has loose ends" with two
    distinct visual indicators.

    Returns ``(current_slug, also_active_slugs)``:
      * ``current_slug`` — phase with the highest ``sort_order`` that has
        ≥1 item in any non-not-started status.
      * ``also_active_slugs`` — earlier phases (sort_order < current) that
        still have ≥1 item in IN_PROGRESS / IN_REVIEW / etc. (NOT
        finished). These are the "loose ends".

    Excluded statuses for "touched":
      - not_started: BACKLOG, NEW, TODO, PROPOSED
    Excluded for "loose end":
      - not_started + finished (DONE, CLOSED, RESOLVED, REMOVED, ABANDONED)
    """
    not_started = {"BACKLOG", "NEW", "TODO", "PROPOSED"}
    finished = {"DONE", "CLOSED", "RESOLVED", "REMOVED", "ABANDONED"}

    # Hotfix 81 (revised in Hotfix 87) — feature-status-aware phase inference
    # with descendant fallback.
    # ----------------------------------------------------------------------
    # The phase classifier only tags TOP-LEVEL features (epics) with
    # ``phase_id``; stories underneath inherit through their parent. Two
    # very different team workflows show up in the wild:
    #
    #   A) Teams that DO advance their feature cards in ADO/Jira
    #      (Plan2Sprint itself, Breakrails). When the PO marks a
    #      feature DONE, the phase should turn GREEN regardless of any
    #      child stories that linger — the team has explicitly signed
    #      off.
    #   B) Teams that DON'T touch the feature card and only drag
    #      stories (Sellixis, MediCare). The feature stays in TODO/
    #      PROPOSED forever even though the underlying work is
    #      progressing; without a fallback the timeline reads every
    #      phase as untouched.
    #
    # Hotfix 81 added an unconditional OR with the child-state — that
    # fixed (B) but broke (A): a DONE feature with one IN_PROGRESS
    # leftover child story made the whole phase show as "loose ends"
    # (cyan), even though the team had clearly closed it out.
    #
    # The corrected rule below is feature-status-aware:
    #
    #   * Feature is FINISHED       (DONE/CLOSED/RESOLVED/REMOVED/ABANDONED)
    #     → phase complete. Children ignored.
    #   * Feature is IN-FLIGHT      (anything past TODO that isn't finished)
    #     → phase touched + in-flight. Children ignored.
    #   * Feature is NOT-STARTED    (TODO/BACKLOG/NEW/PROPOSED)
    #     → fall back to children:
    #         touched   = any child past TODO
    #         in-flight = any child past TODO and not finished
    #
    # This keeps both workflows correct under one rule.
    Child = aliased(WorkItem)
    child_advancing = (
        select(1)
        .where(
            Child.imported_project_id == project.id,
            Child.epic_id == WorkItem.id,
            func.upper(Child.status).notin_(not_started),
        )
        .correlate(WorkItem)
        .exists()
    )
    child_in_flight = (
        select(1)
        .where(
            Child.imported_project_id == project.id,
            Child.epic_id == WorkItem.id,
            func.upper(Child.status).notin_(not_started | finished),
        )
        .correlate(WorkItem)
        .exists()
    )
    feature_in_not_started = func.upper(WorkItem.status).in_(not_started)
    feature_touched = func.upper(WorkItem.status).notin_(not_started)
    feature_in_flight = func.upper(WorkItem.status).notin_(not_started | finished)

    # touched_expr: feature past TODO, OR feature still in TODO + a child past TODO.
    # in_flight_expr: feature in IN_PROGRESS-style state, OR feature in TODO + child in flight.
    # Crucially, when the feature is FINISHED (DONE/CLOSED/etc),
    # in_flight_expr evaluates to false regardless of children — that's
    # the "team explicitly signed off" semantic.
    touched_expr = or_(feature_touched, and_(feature_in_not_started, child_advancing))
    in_flight_expr = or_(feature_in_flight, and_(feature_in_not_started, child_in_flight))

    # Single query — for each phase, count touched items and in-flight
    # items separately. Lets us pick max-touched as current and
    # identify loose ends in one round trip.
    touched_q = await db.execute(
        select(
            ProjectPhase.slug,
            ProjectPhase.sort_order,
            func.sum(case((touched_expr, 1), else_=0)).label("touched"),
            func.sum(case((in_flight_expr, 1), else_=0)).label("in_flight"),
        )
        .join(WorkItem, WorkItem.phase_id == ProjectPhase.id)
        .where(
            ProjectPhase.project_id == project.id,
            WorkItem.imported_project_id == project.id,
        )
        .group_by(ProjectPhase.slug, ProjectPhase.sort_order)
    )
    rows = touched_q.all()

    # Max-touched = current phase.
    current_slug: Optional[str] = None
    current_order: int = -1
    for slug, order, touched, _ in rows:
        if touched and order > current_order:
            current_order = order
            current_slug = slug

    if current_slug is None:
        return None, []

    # Loose ends = phases earlier than current that still have in-flight items.
    also_active: list[str] = []
    for slug, order, _, in_flight in rows:
        if in_flight and order < current_order:
            also_active.append(slug)

    return current_slug, also_active


# ---------------------------------------------------------------------------
# Raw mode
# ---------------------------------------------------------------------------

async def _compute_raw_timeline(
    db: AsyncSession,
    project: ImportedProject,
) -> TimelineDTO:
    """Derive phase dates from ADO/Jira work-item plan dates.

    For each phase (including the final Ready phase):
      planned_start = MIN(work_item.planned_start) across items assigned to
                      the phase (either via phase_id or via their parent
                      feature's phase_id).
      planned_end   = MAX(work_item.planned_end) across the same set.

    If a phase has no work items with dates, its planned_start/planned_end
    remain None — the UI renders the tile with a "TBD" label.

    The Ready phase, by convention, receives the same end date as Deployment
    & Launch (the product is "ready for customers" when launch completes).
    This keeps the tile visible in Raw mode even when no work item has
    "ready" in its title. If Deployment & Launch itself has no end date, so
    does Ready — and Target Launch shows TBD.
    """
    phases = await _load_phases(db, project.id)

    # Build phase-id -> aggregated dates from work items.
    date_q = await db.execute(
        select(
            WorkItem.phase_id,
            func.min(WorkItem.planned_start).label("min_start"),
            func.max(WorkItem.planned_end).label("max_end"),
        )
        .where(
            WorkItem.organization_id == project.organization_id,
            WorkItem.imported_project_id == project.id,
            WorkItem.phase_id.isnot(None),
        )
        .group_by(WorkItem.phase_id)
    )
    per_phase: dict[str, tuple[Optional[datetime], Optional[datetime]]] = {
        row.phase_id: (row.min_start, row.max_end)
        for row in date_q.all()
    }

    timeline_phases: list[TimelinePhase] = []

    for p in phases:
        start, end = per_phase.get(p.id, (None, None))
        # Special handling for Ready: it trails the last non-Ready phase
        # with a planned_end (Hotfix 17 generalised — used to be
        # "deployment-launch" specifically, but cloud-native order may
        # put UAT after Deployment). We fill in its dates after the main
        # loop once we know which phase is last.
        if p.slug == "ready":
            timeline_phases.append(
                TimelinePhase(
                    id=p.id, slug=p.slug, name=p.name, sort_order=p.sort_order,
                    color=p.color, planned_start=None, planned_end=None,
                )
            )
            continue

        timeline_phases.append(
            TimelinePhase(
                id=p.id, slug=p.slug, name=p.name, sort_order=p.sort_order,
                color=p.color, planned_start=start, planned_end=end,
            )
        )

    # Fix up the Ready phase. Hotfix 17 — used to hardcode anchor on
    # ``deployment-launch``, which broke when phases were reordered to
    # cloud-native (UAT now comes after Deployment). Now we anchor Ready
    # on the last non-Ready phase that has an end date — robust to any
    # reordering or to UAT being the last phase with work.
    last_real_end = None
    for tp in sorted(timeline_phases, key=lambda x: x.sort_order):
        if tp.slug == "ready":
            continue
        if tp.planned_end is not None:
            last_real_end = tp.planned_end
    for tp in timeline_phases:
        if tp.slug == "ready":
            tp.planned_start = last_real_end
            tp.planned_end = last_real_end
            break

    # Linearise so the timeline reads left-to-right without overlaps. Work
    # items from different phases are often worked in parallel (e.g. Core
    # Development running alongside Discovery), which produces overlapping
    # min/max date ranges. For dashboard display the phases must appear as
    # strictly sequential blocks — otherwise the timeline looks "jumbled":
    # Mar-Apr overlaps for four phases in a row. We preserve each phase's
    # work-driven *duration* but push its start to the previous phase's end
    # whenever they overlap.
    _linearise_phases(timeline_phases)

    # Target launch date: respect a MANUAL override if the PO set one, else
    # fall back to the project-level target (set when AI plan is approved, in
    # Sprint 3). In pure Raw mode this is typically None → "TBD" in the UI.
    target = project.target_launch_date
    target_source = project.target_launch_source
    if target is None and last_real_end is not None:
        # Even in Raw mode, if ADO/Jira has given us an end date for the
        # last work phase (whatever its slug — generalised in Hotfix 17),
        # that date *is* the effective launch target until the PO
        # overrides or an AI plan lands. We surface it but mark as AUTO
        # so the UI knows it wasn't hand-picked.
        target = last_real_end
        target_source = target_source or "AUTO"

    return TimelineDTO(
        mode=MODE_RAW,
        phases=timeline_phases,
        target_launch_date=target,
        target_launch_source=target_source,
        target_violated=False,
        target_violated_days=0,
    )


# ---------------------------------------------------------------------------
# AI-Optimized & Rebalanced modes
# ---------------------------------------------------------------------------

async def _compute_ai_timeline(
    db: AsyncSession,
    project: ImportedProject,
) -> TimelineDTO:
    """Timeline driven by the approved SprintPlan.

    Design note: the AI sprint generator already writes ``planned_start`` and
    ``planned_end`` onto each work item as part of plan generation. That means
    the per-phase min/max aggregation we do for Raw mode already produces the
    AI-plan-derived dates — we don't have to duplicate sprint-allocation math
    here. What AI mode adds on top is:

      (1) auto-setting ``ImportedProject.target_launch_date`` from the plan's
          ``estimated_end_date`` (unless the PO manually overrode it)
      (2) enforcing the target as a constraint: if any phase ends after the
          target, we flag ``target_violated`` + the number of days by which
          the plan overshoots (we don't auto-shift — the PO either rebalances
          or hand-moves the target)
      (3) anchoring the Ready phase end to ``target_launch_date`` so the
          final handoff tile reflects the committed launch date, not just
          the last deploy date
    """
    plan = await _load_active_plan(db, project.id)

    timeline = await _compute_raw_timeline(db, project)
    timeline.mode = MODE_AI_OPTIMIZED

    # ---- target_launch_date policy ----
    # The source of truth for target_launch_date is whatever the approve
    # handler or the PATCH /target-launch endpoint last wrote. This function
    # no longer *writes* it — it only reads. That means:
    #   * AUTO: set by the most recent plan approval (sprints.py PATCH handler)
    #     or by a rebalance acceptance. We use the stored value as-is.
    #   * MANUAL: set by the PO via the hover-edit. Stored until the PO
    #     approves another plan (the approve handler resets it).
    # If target_launch_date is unset but we have an active plan, backfill on
    # the fly from the plan — this handles projects whose plans were
    # approved before Sprint 3 (or this refactor) shipped.
    if project.target_launch_date is None and plan is not None and plan.estimated_end_date is not None:
        project.target_launch_date = plan.estimated_end_date
        project.target_launch_source = "AUTO"
        await db.commit()

    timeline.target_launch_date = project.target_launch_date
    timeline.target_launch_source = project.target_launch_source

    # ---- AI-mode phase distribution ----
    # In AI / Rebalanced mode the Raw per-phase min/max aggregation produces
    # a "jumbled" timeline: Discovery, Core Dev, Integration, Testing etc.
    # all overlap in Mar-Apr because the team worked them in parallel. The
    # PO dashboard wants a strictly left-to-right display where each phase
    # starts after the previous one ends and the last phase lands exactly
    # on Target Launch.
    #
    # Simpler and more predictable: IGNORE the raw work-item dates and lay
    # out all 7 phases as equal slices of the full project window, from the
    # earliest work-item start (project origin) through target_launch_date.
    # The "current" phase indicator (from ADO/GitHub signals) still tells
    # the PO where the team actually is — the timeline is just a clean
    # linear backdrop.
    if timeline.target_launch_date is not None:
        _equal_slice_linear_timeline(timeline.phases, timeline.target_launch_date)

    # Anchor the Ready phase to the committed launch date.
    if timeline.target_launch_date is not None:
        for p in timeline.phases:
            if p.slug == "ready":
                p.planned_end = timeline.target_launch_date
                if p.planned_start is None or p.planned_start > timeline.target_launch_date:
                    p.planned_start = timeline.target_launch_date
                break

    # Flag violations: any phase that ends past the target.
    target = timeline.target_launch_date
    if target is not None:
        overruns = [
            (p.planned_end - target).days
            for p in timeline.phases
            if p.slug != "ready" and p.planned_end is not None and p.planned_end > target
        ]
        if overruns:
            timeline.target_violated = True
            timeline.target_violated_days = max(overruns)

    return timeline


async def _compute_rebalanced_timeline(
    db: AsyncSession,
    project: ImportedProject,
) -> TimelineDTO:
    """Timeline driven by a rebalanced SprintPlan.

    Functionally identical to AI-Optimized today — the rebalanced plan has
    already been committed with a new ``estimated_end_date`` at acceptance
    time, and target_launch_date was refreshed against it then. This function
    exists as its own branch so that if we later need rebalance-specific
    behaviour (e.g. "before/after" comparison on the hero banner) it has an
    obvious hook point.
    """
    timeline = await _compute_ai_timeline(db, project)
    timeline.mode = MODE_REBALANCED
    return timeline


async def _load_active_plan(db: AsyncSession, project_id: str):
    """Return the most recent APPROVED/SYNCED SprintPlan for the project."""
    try:
        from ..models.sprint_plan import SprintPlan  # type: ignore
    except Exception:  # noqa: BLE001
        return None
    q = await db.execute(
        select(SprintPlan)
        .where(
            SprintPlan.project_id == project_id,
            SprintPlan.status.in_(("APPROVED", "SYNCED", "SYNCED_PARTIAL")),
        )
        .order_by(SprintPlan.created_at.desc())
    )
    return q.scalars().first()


# ---------------------------------------------------------------------------
# Phase distribution (AI / Rebalanced modes)
# ---------------------------------------------------------------------------

def _equal_slice_linear_timeline(
    phases: list["TimelinePhase"],
    target: datetime,
) -> None:
    """Lay out ALL phases as equal, non-overlapping slices of the window
    between the project's origin and ``target``.

    Origin = the earliest non-null ``planned_start`` currently on the
    phases. If nothing is set (brand-new project with no work items yet),
    we anchor to ``target - 7 weeks`` as a sensible default — seven weeks
    is the median Plan2Sprint project so far, and the PO can edit the
    target launch if that's wrong.

    This deliberately discards the per-phase min/max date aggregation. For
    AI / Rebalanced modes the raw aggregation overlaps (parallel work),
    which the PO dashboard reported as "jumbled." Equal slicing gives:

      * strictly sequential phase blocks, left to right
      * the first phase starts at project origin
      * each phase is the same width (1/N of the window)
      * the last phase ends exactly on ``target``

    The "current" phase is conveyed separately via
    ``timeline.current_phase_slug`` (driven by ADO + GitHub signals), so
    losing work-item-accurate dates doesn't hide team progress.
    """
    from datetime import timedelta as _td
    if not phases:
        return

    # Figure out origin.
    starts = [p.planned_start for p in phases if p.planned_start is not None]
    origin = min(starts) if starts else target - _td(weeks=7)
    if origin >= target:
        # Target was edited to earlier than any existing phase start —
        # fall back to a one-day window rather than crashing.
        origin = target - _td(days=1)

    window = (target - origin).total_seconds()
    slice_sec = window / len(phases)
    cursor = origin
    for p in phases:
        p.planned_start = cursor
        cursor = cursor + _td(seconds=slice_sec)
        p.planned_end = cursor
    # Pin the last phase exactly to target so floating-point drift doesn't
    # leave the timeline a millisecond short of the Target Launch KPI.
    phases[-1].planned_end = target


def _linearise_phases(phases: list["TimelinePhase"]) -> None:
    """Push each phase's ``planned_start`` forward so no phase overlaps the
    previous one. Preserves original durations when we can (the work-driven
    length of the phase), otherwise leaves the phase as a zero-length marker
    that ``_distribute_future_phases`` will later redistribute.

    We iterate in ``sort_order`` which the caller guarantees is already the
    natural left-to-right phase order.
    """
    from datetime import timedelta as _td
    prev_end: Optional[datetime] = None
    for p in phases:
        if p.planned_start is None:
            # Nothing to linearise — gap stays as TBD for now. Later stages
            # (AI/Rebalanced distribution) will fill it in.
            prev_end = p.planned_end or prev_end
            continue

        # Is this phase overlapping the tail of the previous one?
        if prev_end is not None and p.planned_start < prev_end:
            # Hold on to the original duration so we preserve the phase's
            # weight (bigger phase = longer bar) after the shift.
            original_duration: Optional[_td] = None
            if p.planned_end is not None and p.planned_end > p.planned_start:
                original_duration = p.planned_end - p.planned_start
            p.planned_start = prev_end
            if original_duration is not None:
                p.planned_end = p.planned_start + original_duration
            elif p.planned_end is None or p.planned_end < p.planned_start:
                # No usable duration — collapse to a zero-length marker at the
                # pushed start. The downstream distributor will expand it.
                p.planned_end = p.planned_start
        prev_end = p.planned_end or prev_end


def _distribute_future_phases(
    phases: list["TimelinePhase"],
    target: datetime,
) -> None:
    """Spread every not-yet-done phase across (now → target) in place.

    Mutates ``phases`` so callers (and ``_persist_phase_dates``) see the new
    boundaries. Past phases — defined as ``planned_end`` strictly in the
    past — stay immutable. The final phase (Ready) is pinned to ``target``
    so the hero banner's target-launch label matches the timeline tile
    exactly.

    Distribution logic:
      - Phases with usable original durations (planned_start < planned_end)
        keep their relative weights → proportional redistribution.
      - Fallback: equal share across future phases when original durations
        aren't available (e.g. a Raw project that just got a plan approved
        and had all future phases at TBD).
    """
    from datetime import timedelta as _td  # local to avoid top-level churn
    now = datetime.now(timezone.utc)
    window = (target - now).total_seconds()
    if window <= 0:
        return

    # Partition phases into past (immutable) and future (rescale targets).
    future_idx = [
        i for i, p in enumerate(phases)
        if p.planned_end is None or p.planned_end > now
    ]
    if not future_idx:
        return

    # Compute each future phase's original duration (if any) for proportional
    # weighting. A phase with missing/zero duration contributes nothing and
    # picks up an equal share instead.
    durations: list[float] = []
    for i in future_idx:
        p = phases[i]
        if p.planned_start and p.planned_end and p.planned_end > p.planned_start:
            durations.append((p.planned_end - p.planned_start).total_seconds())
        else:
            durations.append(0.0)
    total_weight = sum(durations)

    cursor = now
    if total_weight <= 0:
        # Equal share
        slice_sec = window / len(future_idx)
        for i in future_idx:
            phases[i].planned_start = cursor
            cursor = cursor + _td(seconds=slice_sec)
            phases[i].planned_end = cursor
    else:
        # Proportional share
        for i, dur in zip(future_idx, durations):
            frac = (dur / total_weight) if total_weight > 0 else 1.0 / len(future_idx)
            slice_sec = window * frac
            phases[i].planned_start = cursor
            cursor = cursor + _td(seconds=slice_sec)
            phases[i].planned_end = cursor

    # Pin the LAST future phase to the target so FP drift doesn't leave us
    # a millisecond early / late — the hero banner label must match.
    phases[future_idx[-1]].planned_end = target


# ---------------------------------------------------------------------------
# Persistence — write computed dates back to project_phases
# ---------------------------------------------------------------------------

async def _persist_phase_dates(
    db: AsyncSession,
    phases: list[TimelinePhase],
) -> None:
    """Push computed planned_start / planned_end onto the stored phase rows.

    Writes one row at a time rather than a bulk UPDATE so we can handle the
    "dates unchanged" short-circuit without running a query per phase.
    """
    if not phases:
        return
    now = datetime.now(timezone.utc)
    touched = False
    for p in phases:
        q = await db.execute(
            select(ProjectPhase).where(ProjectPhase.id == p.id)
        )
        row = q.scalar_one_or_none()
        if row is None:
            continue
        if row.planned_start == p.planned_start and row.planned_end == p.planned_end:
            continue  # unchanged, skip the UPDATE
        row.planned_start = p.planned_start
        row.planned_end = p.planned_end
        row.updated_at = now
        touched = True
    if touched:
        await db.commit()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

async def _load_project(
    db: AsyncSession, org_id: str, project_id: str
) -> Optional[ImportedProject]:
    q = await db.execute(
        select(ImportedProject).where(
            ImportedProject.id == project_id,
            ImportedProject.organization_id == org_id,
        )
    )
    return q.scalar_one_or_none()


async def _load_phases(
    db: AsyncSession, project_id: str
) -> list[ProjectPhase]:
    q = await db.execute(
        select(ProjectPhase)
        .where(ProjectPhase.project_id == project_id)
        .order_by(ProjectPhase.sort_order, ProjectPhase.created_at)
    )
    return list(q.scalars().all())
