"""add_sprint_plan_project_id_and_ai_fields

Revision ID: efbc1b0a69b3
Revises: c5d8e2f17a03
Create Date: 2026-02-25 21:42:11.075939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbc1b0a69b3'
down_revision: Union[str, None] = 'c5d8e2f17a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project_preferences',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('selected_project_id', sa.String(length=25), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['selected_project_id'], ['imported_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id', name='uq_user_project_pref')
    )
    op.add_column('imported_projects', sa.Column('board_id', sa.String(), nullable=True))
    op.add_column('imported_projects', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('imported_projects', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('iterations', sa.Column('imported_project_id', sa.String(length=25), nullable=True))
    op.create_foreign_key(None, 'iterations', 'imported_projects', ['imported_project_id'], ['id'])
    op.add_column('sprint_plans', sa.Column('project_id', sa.String(length=25), nullable=True))
    op.add_column('sprint_plans', sa.Column('overall_rationale', sa.String(), nullable=True))
    op.add_column('sprint_plans', sa.Column('goal_attainment_confidence', sa.Float(), nullable=True))
    op.add_column('sprint_plans', sa.Column('tool', sa.String(length=10), nullable=True))
    op.add_column('sprint_plans', sa.Column('human_edits', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'sprint_plans', 'imported_projects', ['project_id'], ['id'])
    op.add_column('work_items', sa.Column('imported_project_id', sa.String(length=25), nullable=True))
    op.create_foreign_key(None, 'work_items', 'imported_projects', ['imported_project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_items', type_='foreignkey')
    op.drop_column('work_items', 'imported_project_id')
    op.drop_constraint(None, 'sprint_plans', type_='foreignkey')
    op.drop_column('sprint_plans', 'human_edits')
    op.drop_column('sprint_plans', 'tool')
    op.drop_column('sprint_plans', 'goal_attainment_confidence')
    op.drop_column('sprint_plans', 'overall_rationale')
    op.drop_column('sprint_plans', 'project_id')
    op.drop_constraint(None, 'iterations', type_='foreignkey')
    op.drop_column('iterations', 'imported_project_id')
    op.drop_column('imported_projects', 'synced_at')
    op.drop_column('imported_projects', 'is_active')
    op.drop_column('imported_projects', 'board_id')
    op.drop_table('user_project_preferences')
    # ### end Alembic commands ###
