"""initial_schema

Revision ID: b78fb27e9622
Revises: 
Create Date: 2026-02-21 14:58:44.803194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b78fb27e9622'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('working_hours_start', sa.String(), nullable=False),
    sa.Column('working_hours_end', sa.String(), nullable=False),
    sa.Column('standup_time', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('iterations',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source_tool', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_id', 'source_tool', name='uq_iterations_org_ext_source')
    )
    op.create_table('repositories',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_repositories_org_ext')
    )
    op.create_table('retrospectives',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('iteration_id', sa.String(), nullable=True),
    sa.Column('what_went_well', sa.JSON(), nullable=False),
    sa.Column('what_didnt_go_well', sa.JSON(), nullable=False),
    sa.Column('root_cause_analysis', sa.JSON(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('skill_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('default_capacity', sa.Float(), nullable=False),
    sa.Column('slack_user_id', sa.String(), nullable=True),
    sa.Column('teams_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_team_members_org_ext')
    )
    op.create_table('team_standup_digests',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('iteration_id', sa.String(), nullable=True),
    sa.Column('digest_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sprint_pacing', sa.Float(), nullable=False),
    sa.Column('acknowledged_pct', sa.Float(), nullable=False),
    sa.Column('sprint_health', sa.String(length=50), nullable=False),
    sa.Column('at_risk_items', sa.JSON(), nullable=False),
    sa.Column('blocker_count', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'digest_date', name='uq_team_standup_digests_org_date')
    )
    op.create_table('tool_connections',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('source_tool', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_tool', name='uq_tool_connections_org_source')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('supabase_user_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('supabase_user_id')
    )
    op.create_table('activity_events',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('team_member_id', sa.String(length=25), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source_tool', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('linked_ticket_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_after_hours', sa.Boolean(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_events_org_member_occurred', 'activity_events', ['organization_id', 'team_member_id', 'occurred_at'], unique=False)
    op.create_index('ix_activity_events_org_occurred', 'activity_events', ['organization_id', 'occurred_at'], unique=False)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('actor_id', sa.String(length=25), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('source_channel', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_entries_org_created', 'audit_log_entries', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_entries_org_event_type', 'audit_log_entries', ['organization_id', 'event_type'], unique=False)
    op.create_table('burnout_alerts',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('team_member_id', sa.String(length=25), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('capacity_utilization', sa.Float(), nullable=False),
    sa.Column('consecutive_sprints', sa.Integer(), nullable=False),
    sa.Column('after_hours_frequency', sa.Float(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commits',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('repository_id', sa.String(length=25), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(length=25), nullable=True),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('linked_ticket_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'sha', name='uq_commits_repo_sha')
    )
    op.create_table('health_signals',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('team_member_id', sa.String(length=25), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_signals_org_created', 'health_signals', ['organization_id', 'created_at'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.String(length=25), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('channels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notification_type', name='uq_notification_preferences_user_type')
    )
    op.create_table('retro_action_items',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('retrospective_id', sa.String(length=25), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_carry_forward', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retrospective_id'], ['retrospectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprint_plans',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('iteration_id', sa.String(length=25), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('risk_summary', sa.String(), nullable=True),
    sa.Column('total_story_points', sa.Float(), nullable=True),
    sa.Column('unplanned_items', sa.JSON(), nullable=True),
    sa.Column('ai_model_used', sa.String(), nullable=True),
    sa.Column('rejection_feedback', sa.String(), nullable=True),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('undo_available_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['iterations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standup_reports',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('team_member_id', sa.String(length=25), nullable=False),
    sa.Column('iteration_id', sa.String(), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_items', sa.JSON(), nullable=False),
    sa.Column('in_progress_items', sa.JSON(), nullable=False),
    sa.Column('blockers', sa.JSON(), nullable=False),
    sa.Column('narrative_text', sa.String(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('developer_note', sa.String(), nullable=True),
    sa.Column('is_inactive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'team_member_id', 'report_date', name='uq_standup_reports_org_member_date')
    )
    op.create_table('velocity_profiles',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('team_member_id', sa.String(length=25), nullable=False),
    sa.Column('iteration_id', sa.String(), nullable=True),
    sa.Column('planned_sp', sa.Float(), nullable=False),
    sa.Column('completed_sp', sa.Float(), nullable=False),
    sa.Column('rolling_average', sa.Float(), nullable=True),
    sa.Column('by_ticket_type', sa.JSON(), nullable=True),
    sa.Column('is_cold_start', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_items',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('organization_id', sa.String(length=25), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source_tool', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('story_points', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('labels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('acceptance_criteria', sa.String(), nullable=True),
    sa.Column('epic_id', sa.String(), nullable=True),
    sa.Column('iteration_id', sa.String(length=25), nullable=True),
    sa.Column('assignee_id', sa.String(length=25), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['iteration_id'], ['iterations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_id', 'source_tool', name='uq_work_items_org_ext_source')
    )
    op.create_table('blocker_flags',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('standup_report_id', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ticket_reference', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['standup_report_id'], ['standup_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_assignments',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('sprint_plan_id', sa.String(length=25), nullable=False),
    sa.Column('work_item_id', sa.String(length=25), nullable=False),
    sa.Column('team_member_id', sa.String(length=25), nullable=False),
    sa.Column('story_points', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('risk_flags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('skill_match', sa.JSON(), nullable=True),
    sa.Column('is_human_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sprint_plan_id'], ['sprint_plans.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pull_requests',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('repository_id', sa.String(length=25), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.String(length=25), nullable=True),
    sa.Column('reviewers', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ci_status', sa.String(length=50), nullable=False),
    sa.Column('linked_work_item_id', sa.String(length=25), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_external_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['linked_work_item_id'], ['work_items.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'external_id', name='uq_pull_requests_repo_ext')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pull_requests')
    op.drop_table('plan_assignments')
    op.drop_table('blocker_flags')
    op.drop_table('work_items')
    op.drop_table('velocity_profiles')
    op.drop_table('standup_reports')
    op.drop_table('sprint_plans')
    op.drop_table('retro_action_items')
    op.drop_table('notification_preferences')
    op.drop_index('ix_health_signals_org_created', table_name='health_signals')
    op.drop_table('health_signals')
    op.drop_table('commits')
    op.drop_table('burnout_alerts')
    op.drop_index('ix_audit_log_entries_org_event_type', table_name='audit_log_entries')
    op.drop_index('ix_audit_log_entries_org_created', table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index('ix_activity_events_org_occurred', table_name='activity_events')
    op.drop_index('ix_activity_events_org_member_occurred', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_table('users')
    op.drop_table('tool_connections')
    op.drop_table('team_standup_digests')
    op.drop_table('team_members')
    op.drop_table('retrospectives')
    op.drop_table('repositories')
    op.drop_table('iterations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
